package core;

import java.io.IOException;
import java.nio.file.*;
import java.util.*;
import java.util.stream.Collectors;

public class TextToType {

    static Random rand = new Random(); //whole class uses this
    private static final String [] options = {
            ("src/main/java/io/files/shelley.txt"),
            ("src/main/java/io/files/jordan.txt"),
            ("src/main/java/io/files/text.txt"),
            ("src/main/java/io/files/bronte.txt"),
            ("src/main/java/io/files/thx.txt"),
            ("src/main/java/io/files/starwars.txt")
    };

    /**
     *
     * @param statelength how long the state of the model will be.
     * @return string of text generated by using a markov chain.
     */
    public static String getRandomtxt(int statelength){

        int random = rand.nextInt(options.length); //number of files we have.
//        var chosen = options[random];
        String chosen = options[3]; //for testing purposes.

        try {
            var corpus = (Files.readString(Paths.get(chosen))).split(" "); //corpus is an array of strings split by spaces
            corpus = Arrays.stream(corpus).filter(s-> !(s.equals("\n"))).toArray(String[]::new); //newlines were messing with things.

            var model = generateMarkovModel(statelength, corpus);

            //so we start off with a capital letter...
            var capstarters = model.keySet().stream().filter(k -> k.matches("^[A-Z][a-zA-Z\\p{P}\\s+]*")).toList();

            String key = String.valueOf(pickRandomFrom(capstarters));

            var markovText = new ArrayList<>(Arrays.asList(key.split(" "))); //add both words to new text.

            for (int j = statelength; j <= 60; j++){

               //get the last *statelength* words and join them, this is the key for this current iteration.
                key = String.join(" ", markovText.subList(j-statelength, j));

                String randomNextWord = ""; //placeholder val

                //checking if we're at the end of the corpus--the last word in the text may not be a key if it had no duplicates!
                if (model.containsKey(key)) {
                    randomNextWord = pickRandomFrom(model.get(key)); //selecting random String from the key's corresponding list.
                }
                else {
                    randomNextWord = pickRandomFrom(corpus, statelength);  //append a random 2-word key starter
                }
                markovText.add(randomNextWord);

            }
            return(String.join(" ", markovText));


        } catch (IOException e) {
            throw new RuntimeException(e);
        }

    }


    /** generates a markov model from an array of strings.
     * @param statelength length of the 'state' used to predict the next word in a Markov chain.
     * @return the model
     */
    public static HashMap<String, ArrayList<String>> generateMarkovModel(int statelength, String[] corpus){

        var model = new HashMap<String, ArrayList<String>>();

        for(int i = statelength ; i < corpus.length; i++){ //last word is not included as a key, it doesn't have any 'following words'.

            //populating the Markov Chain HashMap. Keys are for every word in the corpus that has words following it,
            // and the values are a list of words which immediately follow that particular key in the text.
            //if the preceding word is absent from the HashMap, make a new entry with that key and add the word that follows it to a new list!
            //either way, the current word gets added to the list belonging to that key.
            //the list may contain multiples of the same word, which is intended to preserve the probability of a particular following word being selected.

            String currentword = corpus[i];
            //creating a state from the last 'statelength' number of preceding words in
            var preceding = Arrays.stream(corpus, i-statelength, i).collect(Collectors.joining(" "));
            model.computeIfAbsent(preceding, k -> new ArrayList<>()).add(currentword);
        }
        return (model);
    }

//helper functions for random selection of item in a collection. Honestly surprised that's not a built-in function.

    /**
     *
     * @param stringList - a list of Strings.
     * @return a randomly selected String from the provided String list
     */
    public static String pickRandomFrom(List<String> stringList) {
        int randy = rand.nextInt(stringList.size());
        return(stringList.get(randy));

    }

    /**
     *
     * @param stringArray - an array of Strings
     * @return a randomly selected String from the provided String array
     */
    public static String pickRandomFrom(String[] stringArray, int statesize) {
        int randy = rand.nextInt(statesize, stringArray.length);
        //lower bound is state size (so we don't go out of range left)
        //upped bounf is length of array (so we don't go out of range right)
        return(Arrays.stream(stringArray, randy-statesize, randy).collect(Collectors.joining(" ")));
    }


}
